imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [CmfCreateBundle]
    read_from:      %kernel.root_dir%/../web
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration (needed for Jackalope Doctrine DBAL)
doctrine:
    dbal:
        driver:   "%database_driver%"
        charset:  UTF8
        path:     "%database_path%"
        # if using something else than pdo_sqlite as driver, add the
        # parameters in parameters.yml.dist and uncomment the lines below
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        #
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend: "%phpcr_backend%"
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_password%"
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"
        locales:
            fr: ~

# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Cmf Configuration
cmf_create:
    security:
        role: ROLE_ADMIN

cmf_core:
    persistence:
        phpcr: true
    multilang:
        locales:
            - fr

cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true

cmf_media:
    use_imagine: true

cmf_seo:
    persistence:
        phpcr: true
    original_route_pattern: redirect
    title: '%%content_title%% ~ Les amis de soeur Myriam'
    description: 'Association de soutien aux enfants du Vietnam. %%content_title%%'

cmf_simple_cms:
    persistence:
        phpcr:
            document_class: JJK801\Bundle\LADSMBundle\Document\Page

cmf_block:
    persistence:
        phpcr:
            block_basepath: /cms/simple

cmf_menu:
    persistence:
        phpcr:
            use_sonata_admin: true
            content_basepath: /cms/simple

liip_imagine:
    filter_sets:
        home_slideshow:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [600, 300], mode: outbound }

# Menu Configuration
knp_menu:
    twig: true

sonata_user:
    security_acl: true
    manager_type: orm
    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
    profile:
        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
        # Customize user portal menu by setting links
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_seo:
    page:
        title: 'Les amis de soeur Myriam'
        metas:
            name:
                description: 'Association de soutien aux enfants du Vietnam.'
                keywords:    'association, enfants, vietnam, france'

sonata_admin:
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list }
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
            blocks:
                label: Blocks
                items:
                    - cmf_block.imagine.slideshow_admin
            pages:
                label: Pages
                items:
                    - cmf_simple_cms.persistence.phpcr.admin.page
                    - jjk801_ladsm.persistence.phpcr.admin.task
                    - jjk801_ladsm.persistence.phpcr.admin.news
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
            user:
                label: User
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
    extensions:
        cmf_seo.admin_extension:
                admins:
                    - cmf_simple_cms.persistence.phpcr.admin.page
                implements:
                    - Symfony\Cmf\Bundle\SeoBundle\SeoAwareInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_core.admin_extension.translatable:
            excludes:
                - cmf_block.imagine.slideshow_imagine_admin
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
        cmf_routing.admin_extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock
            image: '/images/icons/slideshow16.png'
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock:
            valid_children: []
            image: '/images/icons/image16.png'
        Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock:
            valid_children:
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SimpleBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ContainerBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ReferenceBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ActionBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\SlideshowBlock
                - Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\RssBlock
        JJK801\Bundle\LADSMBundle\Document\Page:
            valid_children:
                - JJK801\Bundle\LADSMBundle\Document\Page
            image: '/images/icons/webpage16.png'
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\Menu:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
            image: '/images/icons/route16.png'
        Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode
            image: '/images/icons/route16.png'

# Cmf Create Configuration
fos_rest:
    view:
        formats:
            json: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class:     JJK801\Bundle\LADSMBundle\Entity\User
    group:
        group_class:   Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager