JJK801\Bundle\LADSMBundle\Document\News:
    repositoryClass: JJK801\Bundle\LADSMBundle\Repository\News
    fields:
        slugKey:
            type: string
            property: slug_key
        createdAt:
            type: date
            property: "jcr:created"
        updatedAt:
            type: date
            property: "jcr:lastModified"
            nullable: true